### ISSUE TITLE
Network Errors Logged On Page Load

### ISSUE THREAD

**Issue by jeffscottbrown** [grails/grails-forge-ui#44]
<img width="1350" alt="Screenshot 2024-02-13 at 9 15 03 AM" src="https://github.com/grails/grails-forge-ui/assets/15482/55fd629d-8509-413c-8e2a-230e2c631a7c">

When I load the page in the browser I am seeing errors sending requests to https://prev.grails.org/versions  and  https://next.grails.org/versions coming out of MicronautStarterSDK.js.

FYI: https://github.com/micronaut-projects/micronaut-starter-ui/issues/102 looks like it might be tangentially related, but probably not the same issue.

**Comment by jamesfredley** [comment]
This has been resolved and there are now 5 versions on https://start.grails.org/

https://github.com/grails/grails-forge-ui/pull/45
https://github.com/grails/grails-forge/issues/380
